name: deact_gen
description: A sample command-line application.
version: 1.0.0
homepage: https://github.com/blimster/deact_gen

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  resource: ^2.1.6
  json_annotation: ^3.0.0

dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^3.2.0
